### ISSUE TITLE
 invalid memory address error in GetPDUAddressInformation 

### ISSUE THREAD

**Issue by gruyaume** [omec-project/gnbsim#243]
## Description

I was working on a change in the SMF and encountered an issue when running end to end tests with gnbsim. While in normal scenarios we should not encounter this issue, it is expected that gnbsim errors out cleanly and does not panic.

## Environment
- gnbsim version: `1.4.3`

## Logs
```
2024-10-17T22:15:53Z [INFO][GNBSIM][RealUe][imsi-001010100007487] Handling: PDU-SESSION-ESTABLISHMENT-ACCEPT-EVENT
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe81e5b]

goroutine 58 [running]:
github.com/omec-project/nas/nasType.(*PDUAddress).GetPDUAddressInformation(...)
	/root/go/pkg/mod/github.com/omec-project/nas@v1.3.0/nasType/NAS_PDUAddress.go:62
github.com/omec-project/gnbsim/realue.HandlePduSessEstAcceptEvent(0xc0005aafc0, {0x137d508?, 0xc0003b6370})
	/root/parts/gnbsim/build/realue/handler.go:239 +0x11b
github.com/omec-project/gnbsim/realue.HandleEvents(0xc0005aafc0)
	/root/parts/gnbsim/build/realue/realue.go:47 +0x3af
github.com/omec-project/gnbsim/realue.Init(0xc0005aafc0)
	/root/parts/gnbsim/build/realue/realue.go:16 +0x228
github.com/omec-project/gnbsim/simue.Init.func1()
	/root/parts/gnbsim/build/simue/simue.go:38 +0x53
created by github.com/omec-project/gnbsim/simue.Init in goroutine 1
	/root/parts/gnbsim/build/simue/simue.go:36 +0x148
```

**Comment by gab-arrobo** [comment]
@thakurajayL, how would you like to proceed about this?

**Comment by thakurajayL** [comment]
It seems difficult to know why PDU address was missing. It would be easy to fix if it is reproducible in multiple setup.

**Comment by gab-arrobo** [comment]
@gruyaume, how can we reproduce this issue?

**Comment by gab-arrobo** [comment]
@gruyaume, any update about this issue?
